[package]
name = "rasn-compiler-tests"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rasn-compiler-derive = { path = "../rasn-compiler-derive" }

[dev-dependencies]
bitvec = { version = "1" }
bitvec-nom = { version = "0.2" }
rasn = "0.9.5"
rasn-kerberos = "0.9.5"
bytes = "1.4.0"
num-bigint = "0.4.4"

