[package]
name = "rasn-compiler"
authors = ["Kevin Westphal"]
version = "0.1.0"
edition = "2021"

[lib]
name = "rasn_compiler"
path = "src/lib.rs"

[[bin]]
required-features = ["cli"]
name = "rasn_compiler_cli"
path = "src/bin.rs"

[features]
cli = []

[dependencies]
nom = "7.1.3"

[dependencies.num]
version = "0.4"
default-features = false
